const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = __dirname;
const SOURCE_DIR = path.join(ROOT, "data", "vendor", "player_career_chunks");
const OUTPUT_DIR = path.join(ROOT, "data", "vendor", "player_career_year_chunks");
const MANIFEST_PATH = path.join(ROOT, "data", "vendor", "player_career_year_manifest.js");
const PART_FILES = [
  "part-001.js",
  "part-002.js",
  "part-003.js",
  "part-004.js",
  "part-005.js",
];

function parseCsv(text) {
  const rows = [];
  if (!text) return rows;

  let current = "";
  let row = [];
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === "\"") {
      if (inQuotes && next === "\"") {
        current += "\"";
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (!inQuotes && char === ",") {
      row.push(current);
      current = "";
      continue;
    }

    if (!inQuotes && (char === "\n" || char === "\r")) {
      if (char === "\r" && next === "\n") index += 1;
      row.push(current);
      current = "";
      if (row.some((cell) => cell !== "")) rows.push(row);
      row = [];
      continue;
    }

    current += char;
  }

  row.push(current);
  if (row.some((cell) => cell !== "")) rows.push(row);
  return rows;
}

function csvEscape(value) {
  const text = String(value ?? "");
  if (!/[",\r\n]/.test(text)) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

function serializeCsvRow(row) {
  return row.map(csvEscape).join(",");
}

function extractChunkText(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const sandbox = { window: {} };
  vm.runInNewContext(source, sandbox, { filename: path.basename(filePath) });
  const chunkMap = sandbox.window.PLAYER_CAREER_CSV_CHUNKS || {};
  const keys = Object.keys(chunkMap);
  if (keys.length !== 1) {
    throw new Error(`Expected one chunk in ${filePath}, found ${keys.length}`);
  }
  return String(chunkMap[keys[0]] ?? "");
}

function compareSeasonStrings(left, right) {
  const leftYear = Number(left);
  const rightYear = Number(right);
  if (Number.isFinite(leftYear) && Number.isFinite(rightYear) && leftYear !== rightYear) {
    return rightYear - leftYear;
  }
  return String(right).localeCompare(String(left), undefined, { numeric: true, sensitivity: "base" });
}

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const bySeason = new Map();
let header = null;

for (const fileName of PART_FILES) {
  const filePath = path.join(SOURCE_DIR, fileName);
  const csvText = extractChunkText(filePath);
  const rows = parseCsv(csvText);
  if (!rows.length) continue;

  if (!header) {
    header = rows[0].map((cell) => String(cell).trim());
  }

  const seasonIndex = header.indexOf("season");
  if (seasonIndex < 0) {
    throw new Error("player_career CSV is missing a season column");
  }

  const firstRow = rows[0].map((cell) => String(cell).trim());
  const startIndex = firstRow.length === header.length && firstRow[0] === header[0] ? 1 : 0;

  for (const row of rows.slice(startIndex)) {
    const season = String(row[seasonIndex] ?? "").trim();
    if (!season) continue;
    if (!bySeason.has(season)) bySeason.set(season, []);
    bySeason.get(season).push(serializeCsvRow(row));
  }
}

if (!header) {
  throw new Error("Unable to read player_career header");
}

const seasons = Array.from(bySeason.keys()).sort(compareSeasonStrings);
const counts = Object.fromEntries(seasons.map((season) => [season, bySeason.get(season).length]));
const manifest = {
  years: seasons,
  initialYears: seasons.length ? [seasons[0]] : [],
  counts,
};

const manifestSource = [
  "// Generated by build_player_career_year_chunks.js",
  `// ${new Date().toISOString()}`,
  "window.PLAYER_CAREER_YEAR_MANIFEST = " + JSON.stringify(manifest, null, 2) + ";",
  "",
].join("\n");
fs.writeFileSync(MANIFEST_PATH, manifestSource, "utf8");

const headerRow = header.map(csvEscape).join(",");
for (const season of seasons) {
  const rows = bySeason.get(season) || [];
  const csvRows = [headerRow, ...rows].join("\r\n") + "\r\n";
  const chunkSource = [
    "window.PLAYER_CAREER_YEAR_CSV_CHUNKS = window.PLAYER_CAREER_YEAR_CSV_CHUNKS || {};",
    `window.PLAYER_CAREER_YEAR_CSV_CHUNKS[${JSON.stringify(season)}] = ${JSON.stringify(csvRows)};`,
    "",
  ].join("\n");
  fs.writeFileSync(path.join(OUTPUT_DIR, `${season}.js`), chunkSource, "utf8");
}

console.log(JSON.stringify({
  seasons: seasons.length,
  latestSeason: seasons[0] || "",
  earliestSeason: seasons[seasons.length - 1] || "",
  totalRows: seasons.reduce((sum, season) => sum + (counts[season] || 0), 0),
}, null, 2));
