from __future__ import annotations

import csv
import json
import re
from datetime import datetime, timezone
from pathlib import Path

csv.field_size_limit(1024 * 1024 * 128)

ROOT = Path(__file__).resolve().parent
PROJECTS_ROOT = ROOT.parent
SOURCE_CSV = PROJECTS_ROOT / "multi-explorer-site-data" / "generated" / "player_career_rows.csv"
OUTPUT_DIR = ROOT / "data" / "vendor" / "player_career_year_chunks"
MANIFEST_PATH = ROOT / "data" / "vendor" / "player_career_year_manifest.js"
TEMP_DIR = OUTPUT_DIR / "_tmp"
CHUNK_GLOBAL = "PLAYER_CAREER_YEAR_CSV_CHUNKS"
MIN_YEAR = 1998


def canonical_season_label(value: object) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    match = re.search(r"(\d{4})\s*[-/]\s*(\d{2,4})", text)
    if match:
        end_part = match.group(2)
        return str(int(f"20{end_part}" if len(end_part) == 2 else end_part))
    years = re.findall(r"\d{4}", text)
    if years:
        return str(int(years[-1]))
    try:
        return str(int(round(float(text))))
    except ValueError:
        return text


def compare_seasons(left: str) -> tuple[int, str]:
    try:
        return (-int(left), left)
    except ValueError:
        return (0, left)


def main() -> None:
    if not SOURCE_CSV.exists():
        raise FileNotFoundError(f"Missing source CSV: {SOURCE_CSV}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    TEMP_DIR.mkdir(parents=True, exist_ok=True)

    counts: dict[str, int] = {}
    temp_paths: dict[str, Path] = {}
    temp_handles: dict[str, object] = {}
    temp_writers: dict[str, csv.DictWriter] = {}

    try:
        with SOURCE_CSV.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            if not reader.fieldnames:
                raise ValueError("Player/Career CSV is missing headers")
            fieldnames = list(reader.fieldnames)
            if "season" not in fieldnames:
                raise ValueError("Player/Career CSV is missing a season column")

            for row in reader:
                season = canonical_season_label(row.get("season"))
                try:
                    season_year = int(season)
                except ValueError:
                    continue
                if season_year < MIN_YEAR:
                    continue
                row["season"] = season
                if season not in temp_writers:
                    temp_path = TEMP_DIR / f"{season}.csv"
                    temp_paths[season] = temp_path
                    temp_handle = temp_path.open("w", encoding="utf-8", newline="")
                    temp_handles[season] = temp_handle
                    writer = csv.DictWriter(temp_handle, fieldnames=fieldnames)
                    writer.writeheader()
                    temp_writers[season] = writer
                temp_writers[season].writerow(row)
                counts[season] = counts.get(season, 0) + 1
    finally:
        for handle in temp_handles.values():
            handle.close()

    seasons = sorted(counts.keys(), key=compare_seasons)
    manifest = {
        "years": seasons,
        "initialYears": [seasons[0]] if seasons else [],
        "counts": {season: counts[season] for season in seasons},
        "latestYear": seasons[0] if seasons else "",
        "minYear": MIN_YEAR,
    }
    manifest_source = "\n".join([
        "// Generated by build_player_career_year_chunks.py",
        f"// {datetime.now(timezone.utc).isoformat()}",
        "window.PLAYER_CAREER_YEAR_MANIFEST = " + json.dumps(manifest, indent=2) + ";",
        "",
    ])
    MANIFEST_PATH.write_text(manifest_source, encoding="utf-8")

    expected_chunk_names = {f"{season}.js" for season in seasons}
    for path in OUTPUT_DIR.glob("*.js"):
        if path.name not in expected_chunk_names:
            path.unlink()

    for season in seasons:
        csv_text = temp_paths[season].read_text(encoding="utf-8")
        chunk_source = "\n".join([
            f"window.{CHUNK_GLOBAL} = window.{CHUNK_GLOBAL} || {{}};",
            f"window.{CHUNK_GLOBAL}[{json.dumps(season)}] = {json.dumps(csv_text)};",
            "",
        ])
        (OUTPUT_DIR / f"{season}.js").write_text(chunk_source, encoding="utf-8")

    for path in TEMP_DIR.glob("*.csv"):
        path.unlink()
    if TEMP_DIR.exists():
        TEMP_DIR.rmdir()

    print(json.dumps({
        "seasons": len(seasons),
        "latestSeason": seasons[0] if seasons else "",
        "earliestSeason": seasons[-1] if seasons else "",
        "totalRows": sum(counts.values()),
    }, indent=2))


if __name__ == "__main__":
    main()
