const fs = require("fs");
const path = require("path");
const ROOT = __dirname;
const SOURCE_FILE = path.join(ROOT, "..", "multi-explorer-site-data", "generated", "player_career_rows.csv");
const OUTPUT_DIR = path.join(ROOT, "data", "vendor", "player_career_year_chunks");
const MANIFEST_PATH = path.join(ROOT, "data", "vendor", "player_career_year_manifest.js");
const MIN_YEAR = 1998;

function parseCsv(text) {
  const rows = [];
  if (!text) return rows;

  let current = "";
  let row = [];
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === "\"") {
      if (inQuotes && next === "\"") {
        current += "\"";
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (!inQuotes && char === ",") {
      row.push(current);
      current = "";
      continue;
    }

    if (!inQuotes && (char === "\n" || char === "\r")) {
      if (char === "\r" && next === "\n") index += 1;
      row.push(current);
      current = "";
      if (row.some((cell) => cell !== "")) rows.push(row);
      row = [];
      continue;
    }

    current += char;
  }

  row.push(current);
  if (row.some((cell) => cell !== "")) rows.push(row);
  return rows;
}

function csvEscape(value) {
  const text = String(value ?? "");
  if (!/[",\r\n]/.test(text)) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

function serializeCsvRow(row) {
  return row.map(csvEscape).join(",");
}

function loadAllRows() {
  return parseCsv(fs.readFileSync(SOURCE_FILE, "utf8"));
}

function canonicalSeasonLabel(value) {
  const text = String(value ?? "").trim();
  if (!text) return "";
  const match = text.match(/(\d{4})\s*[-/]\s*(\d{2,4})/);
  if (match) {
    const endPart = match[2];
    return String(Number(endPart.length === 2 ? `20${endPart}` : endPart));
  }
  const years = text.match(/\d{4}/g);
  if (years?.length) return String(Number(years[years.length - 1]));
  const numeric = Number(text);
  return Number.isFinite(numeric) ? String(Math.round(numeric)) : text;
}

function compareSeasonStrings(left, right) {
  return Number(right) - Number(left);
}

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const rows = loadAllRows();
if (!rows.length) {
  throw new Error("Unable to read player_career bundle");
}

const header = rows[0].map((cell) => String(cell).trim());
const seasonIndex = header.indexOf("season");
if (seasonIndex < 0) {
  throw new Error("player_career CSV is missing a season column");
}

const bySeason = new Map();
for (const inputRow of rows.slice(1)) {
  const row = inputRow.slice();
  const season = canonicalSeasonLabel(row[seasonIndex]);
  const seasonYear = Number(season);
  if (!season || !Number.isFinite(seasonYear) || seasonYear < MIN_YEAR) continue;
  row[seasonIndex] = season;
  if (!bySeason.has(season)) bySeason.set(season, []);
  bySeason.get(season).push(serializeCsvRow(row));
}

const seasons = Array.from(bySeason.keys()).sort(compareSeasonStrings);
const counts = Object.fromEntries(seasons.map((season) => [season, bySeason.get(season).length]));
const expectedChunkFiles = new Set(seasons.map((season) => `${season}.js`));
for (const entry of fs.readdirSync(OUTPUT_DIR, { withFileTypes: true })) {
  if (!entry.isFile() || !entry.name.endsWith(".js")) continue;
  if (expectedChunkFiles.has(entry.name)) continue;
  fs.rmSync(path.join(OUTPUT_DIR, entry.name));
}
const manifest = {
  years: seasons,
  initialYears: seasons.length ? [seasons[0]] : [],
  counts,
  latestYear: seasons[0] || "",
  minYear: MIN_YEAR,
};

const manifestSource = [
  "// Generated by build_player_career_year_chunks.js",
  `// ${new Date().toISOString()}`,
  "window.PLAYER_CAREER_YEAR_MANIFEST = " + JSON.stringify(manifest, null, 2) + ";",
  "",
].join("\n");
fs.writeFileSync(MANIFEST_PATH, manifestSource, "utf8");

const headerRow = header.map(csvEscape).join(",");
for (const season of seasons) {
  const csvRows = [headerRow, ...(bySeason.get(season) || [])].join("\r\n") + "\r\n";
  const chunkSource = [
    "window.PLAYER_CAREER_YEAR_CSV_CHUNKS = window.PLAYER_CAREER_YEAR_CSV_CHUNKS || {};",
    `window.PLAYER_CAREER_YEAR_CSV_CHUNKS[${JSON.stringify(season)}] = ${JSON.stringify(csvRows)};`,
    "",
  ].join("\n");
  fs.writeFileSync(path.join(OUTPUT_DIR, `${season}.js`), chunkSource, "utf8");
}

console.log(JSON.stringify({
  seasons: seasons.length,
  latestSeason: seasons[0] || "",
  earliestSeason: seasons[seasons.length - 1] || "",
  totalRows: seasons.reduce((sum, season) => sum + (counts[season] || 0), 0),
}, null, 2));
